-- Squashed PostgreSQL baseline.
--
-- Replaces the MariaDB migration history V1.0.0..V18.0.1 (see git history). The port to
-- PostgreSQL made replaying that history pointless: it was MariaDB-specific throughout
-- (AUTO_INCREMENT, enum, MODIFY, INSERT IGNORE, SET FOREIGN_KEY_CHECKS) and contained
-- churn that cancelled itself out (V18.0.1 converted the BLOBs V18.0.0 had just created).
-- This file expresses the resulting schema directly.
--
-- Identity columns are GENERATED BY DEFAULT (not ALWAYS) so the MariaDB->PostgreSQL data
-- import can insert explicit primary keys; the import resets each sequence afterwards.

CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    timezone VARCHAR(255) NOT NULL
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
);

CREATE INDEX fk_user_roles_role ON user_roles (role_id);

CREATE TABLE api_keys (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(64) NOT NULL UNIQUE,
    key_hash     VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ(6),
    revoked_at   TIMESTAMPTZ(6)
);

CREATE TABLE api_key_roles (
    api_key_id BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    PRIMARY KEY (api_key_id, role_id),
    CONSTRAINT fk_apikey_roles_apikey FOREIGN KEY (api_key_id) REFERENCES api_keys (id) ON DELETE CASCADE,
    CONSTRAINT fk_apikey_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
);

CREATE INDEX fk_apikey_roles_role ON api_key_roles (role_id);

CREATE TABLE feed (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on TIMESTAMPTZ(6) NOT NULL,
    title      VARCHAR(255) NOT NULL,
    url        VARCHAR(255) NOT NULL,
    cookie     TEXT
);

-- process_state was a MariaDB enum; PostgreSQL has no equivalent that Hibernate's
-- @Enumerated(STRING) mapping validates against, so it is a plain VARCHAR guarded by a
-- CHECK constraint listing the ProcessState values.
CREATE TABLE feed_item_to_process (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on    TIMESTAMPTZ(6) NOT NULL,
    updated_on    TIMESTAMPTZ(6) NOT NULL,
    feed_id       BIGINT NOT NULL,
    ref_id        VARCHAR(255) NOT NULL,
    title         VARCHAR(255) NOT NULL,
    url           TEXT NOT NULL,
    process_state VARCHAR(255) NOT NULL,
    failure_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "UKqq528yv0hp5asschk1c0j6yml" UNIQUE (ref_id),
    CONSTRAINT "FKooyif7a1yt9yp78sv8syo41ue" FOREIGN KEY (feed_id) REFERENCES feed (id),
    CONSTRAINT feed_item_to_process_process_state_check
        CHECK (process_state IN ('NEW', 'IN_PROGRESS', 'DONE', 'ERROR', 'FAILED'))
);

CREATE INDEX "FKooyif7a1yt9yp78sv8syo41ue" ON feed_item_to_process (feed_id);

CREATE TABLE news (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on            TIMESTAMPTZ(6) NOT NULL,
    url                   TEXT NOT NULL,
    text                  TEXT NOT NULL,
    title                 VARCHAR(255) NOT NULL,
    feed_id               BIGINT NOT NULL,
    original_feed_item_id BIGINT NOT NULL,
    advertising           BOOLEAN,
    timely                BOOLEAN,
    impact_scope          VARCHAR(20),
    CONSTRAINT "FK427c1n2b9pxdi2iv4j3ik98ew" FOREIGN KEY (original_feed_item_id) REFERENCES feed_item_to_process (id),
    CONSTRAINT "FKd48cwwuqwbi8twwn4rpe0vpuu" FOREIGN KEY (feed_id) REFERENCES feed (id)
);

CREATE INDEX "FK427c1n2b9pxdi2iv4j3ik98ew" ON news (original_feed_item_id);
CREATE INDEX "FKd48cwwuqwbi8twwn4rpe0vpuu" ON news (feed_id);
CREATE INDEX idx_news_created_on_desc_id ON news (created_on DESC, id);

CREATE TABLE tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(255)
);

CREATE TABLE news_tags (
    news_id BIGINT NOT NULL,
    tags_id BIGINT NOT NULL,
    PRIMARY KEY (news_id, tags_id),
    CONSTRAINT "FKi06sdgpsvq2oxtharq5q1rc3x" FOREIGN KEY (news_id) REFERENCES news (id),
    CONSTRAINT "FK30dfp9jff63kipjrue2s4931i" FOREIGN KEY (tags_id) REFERENCES tags (id)
);

CREATE INDEX "FK30dfp9jff63kipjrue2s4931i" ON news_tags (tags_id);

CREATE TABLE tag_group (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_on DATE NOT NULL,
    title      VARCHAR(255) NOT NULL
);

-- Intentionally no unique constraint on tags_id: V5.0.0 dropped it in favour of a plain
-- index, so a tag may belong to several tag groups.
CREATE TABLE tag_group_tags (
    tag_group_id BIGINT NOT NULL,
    tags_id      BIGINT NOT NULL,
    CONSTRAINT "FKf4l3kwe7ky9w51nhe045yvo2g" FOREIGN KEY (tag_group_id) REFERENCES tag_group (id),
    CONSTRAINT "FKhx1di0tc9w7cqdriua5qtykxm" FOREIGN KEY (tags_id) REFERENCES tags (id)
);

CREATE INDEX "FKf4l3kwe7ky9w51nhe045yvo2g" ON tag_group_tags (tag_group_id);
CREATE INDEX "UKh65wfdwb53nx40tjbqdd26wko" ON tag_group_tags (tags_id);

CREATE TABLE news_vote (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id   BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    vote_date DATE NOT NULL,
    CONSTRAINT unique_vote UNIQUE (news_id, user_id, vote_date),
    CONSTRAINT fk_news_vote_news_id FOREIGN KEY (news_id) REFERENCES news (id),
    CONSTRAINT fk_news_vote_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX fk_news_vote_user_id ON news_vote (user_id);

CREATE TABLE daily_digest (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT NOT NULL,
    created_on TIMESTAMPTZ(6) NOT NULL
);

-- Spring Authorization Server persistence for the MCP OAuth2 endpoints. Dynamic Client
-- Registration (RFC 7591) creates clients at runtime, so these stores must be JDBC-backed
-- to survive restarts. JdbcOAuth2AuthorizationService binds the attributes / *_value /
-- *_metadata columns as JSON strings, so they are text types rather than BLOBs. These
-- tables are not JPA-mapped, so they follow Spring's reference schema rather than
-- Hibernate's expectations.
CREATE TABLE oauth2_registered_client (
    id                            VARCHAR(100) NOT NULL PRIMARY KEY,
    client_id                     VARCHAR(100) NOT NULL,
    client_id_issued_at           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_secret                 VARCHAR(200) DEFAULT NULL,
    client_secret_expires_at      TIMESTAMP(6) DEFAULT NULL,
    client_name                   VARCHAR(200) NOT NULL,
    client_authentication_methods VARCHAR(1000) NOT NULL,
    authorization_grant_types     VARCHAR(1000) NOT NULL,
    redirect_uris                 VARCHAR(1000) DEFAULT NULL,
    post_logout_redirect_uris     VARCHAR(1000) DEFAULT NULL,
    scopes                        VARCHAR(1000) NOT NULL,
    client_settings               VARCHAR(2000) NOT NULL,
    token_settings                VARCHAR(2000) NOT NULL
);

CREATE TABLE oauth2_authorization_consent (
    registered_client_id VARCHAR(100) NOT NULL,
    principal_name       VARCHAR(200) NOT NULL,
    authorities          VARCHAR(1000) NOT NULL,
    PRIMARY KEY (registered_client_id, principal_name)
);

CREATE TABLE oauth2_authorization (
    id                            VARCHAR(100) NOT NULL PRIMARY KEY,
    registered_client_id          VARCHAR(100) NOT NULL,
    principal_name                VARCHAR(200) NOT NULL,
    authorization_grant_type      VARCHAR(100) NOT NULL,
    authorized_scopes             VARCHAR(1000) DEFAULT NULL,
    attributes                    TEXT DEFAULT NULL,
    state                         VARCHAR(500) DEFAULT NULL,
    authorization_code_value      TEXT DEFAULT NULL,
    authorization_code_issued_at  TIMESTAMP(6) DEFAULT NULL,
    authorization_code_expires_at TIMESTAMP(6) DEFAULT NULL,
    authorization_code_metadata   TEXT DEFAULT NULL,
    access_token_value            TEXT DEFAULT NULL,
    access_token_issued_at        TIMESTAMP(6) DEFAULT NULL,
    access_token_expires_at       TIMESTAMP(6) DEFAULT NULL,
    access_token_metadata         TEXT DEFAULT NULL,
    access_token_type             VARCHAR(100) DEFAULT NULL,
    access_token_scopes           VARCHAR(1000) DEFAULT NULL,
    oidc_id_token_value           TEXT DEFAULT NULL,
    oidc_id_token_issued_at       TIMESTAMP(6) DEFAULT NULL,
    oidc_id_token_expires_at      TIMESTAMP(6) DEFAULT NULL,
    oidc_id_token_metadata        TEXT DEFAULT NULL,
    refresh_token_value           TEXT DEFAULT NULL,
    refresh_token_issued_at       TIMESTAMP(6) DEFAULT NULL,
    refresh_token_expires_at      TIMESTAMP(6) DEFAULT NULL,
    refresh_token_metadata        TEXT DEFAULT NULL,
    user_code_value               TEXT DEFAULT NULL,
    user_code_issued_at           TIMESTAMP(6) DEFAULT NULL,
    user_code_expires_at          TIMESTAMP(6) DEFAULT NULL,
    user_code_metadata            TEXT DEFAULT NULL,
    device_code_value             TEXT DEFAULT NULL,
    device_code_issued_at         TIMESTAMP(6) DEFAULT NULL,
    device_code_expires_at        TIMESTAMP(6) DEFAULT NULL,
    device_code_metadata          TEXT DEFAULT NULL
);

CREATE INDEX idx_oauth2_authorization_principal ON oauth2_authorization (principal_name);

-- Reference data ------------------------------------------------------------------------

INSERT INTO roles (name) VALUES ('ADMIN'), ('USER'), ('READONLY')
    ON CONFLICT (name) DO NOTHING;

-- Placeholder BCrypt hashes; the real secrets are written by StartupPasswordSyncer at boot
-- from the AUTH_*_PASSWORD / SCRAPER_API_KEY env vars. Each placeholder is structurally a
-- valid BCrypt string (so passwordEncoder.matches() returns false instead of throwing) but
-- contains no real password, leaving the account unusable until startup syncs it.
INSERT INTO users (email, password, timezone) VALUES
    ('write',    '$2a$10$xxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Europe/Berlin'),
    ('actuator', '$2a$10$xxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Europe/Berlin'),
    ('swagger',  '$2a$10$xxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Europe/Berlin'),
    ('read',     '$2a$10$xxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Europe/Berlin')
    ON CONFLICT (email) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
JOIN roles r ON TRUE
WHERE (u.email = 'write'    AND r.name IN ('ADMIN', 'USER', 'READONLY'))
   OR (u.email = 'actuator' AND r.name IN ('ADMIN', 'USER', 'READONLY'))
   OR (u.email = 'swagger'  AND r.name IN ('ADMIN', 'USER', 'READONLY'))
   OR (u.email = 'read'     AND r.name = 'READONLY')
    ON CONFLICT DO NOTHING;

INSERT INTO api_keys (name, key_hash)
VALUES ('scraper', '$2a$10$xxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    ON CONFLICT (name) DO NOTHING;

INSERT INTO api_key_roles (api_key_id, role_id)
SELECT ak.id, r.id
FROM api_keys ak
JOIN roles r ON r.name IN ('ADMIN', 'USER', 'READONLY')
WHERE ak.name = 'scraper'
    ON CONFLICT DO NOTHING;

INSERT INTO feed (created_on, title, url) VALUES
    (NOW(), 'heise',   'https://www.heise.de/rss/heise-atom.xml'),
    (NOW(), 'spiegel', 'https://www.spiegel.de/schlagzeilen/index.rss');
