services:
  frontend:
    build: news-frontend
    ports:
      - "5173:80"
    environment:
      - API_URL=http://localhost:8888
      - API_USER=read
      - API_PASSWORD=read
  backend:
    build: news-backend
    ports:
      - "8888:8888"
    environment:
      - DB_HOST=database
      - AUTH_ACTUATOR_PASSWORD=xxx
      - AUTH_SWAGGER_PASSWORD=xxx
      - AUTH_WRITE_PASSWORD=write
      - APP_EXTERNAL_DOMAIN=http://localhost:8888
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=news_prod
      - MYSQL_USER=news
      - MYSQL_PASSWORD=news
    healthcheck:
      test: mariadb -unews -pnews news_prod -e "select 1"
      interval: 10s
      timeout: 60s
      retries: 5
    ports:
      - "3306:3306"
  scraper:
    build: scraper
    environment:
      - NO_ENV_FILE=true
      - USERNAME=${USERNAME:?No username defined}
      - PASSWORD=${PASSWORD:?No password defined}
      - URL=${URL:?No URL defined}
      - MODEL=${MODEL:?No model defined}
      - API_KEY=${API_KEY:?No API KEY defined}
      - GENERATION_ENGINE=${GENERATION_ENGINE:?No generation engine defined}
  scraper-tags:
    build: scraper
    command: ["./run.sh", "taggroups"]
    environment:
      - USERNAME=${USERNAME:?No username defined}
      - PASSWORD=${PASSWORD:?No password defined}
      - URL=${URL:?No URL defined}
      - MODEL=${MODEL:?No model defined}
      - API_KEY=${API_KEY:?No API KEY defined}
      - GENERATION_ENGINE=${GENERATION_ENGINE:?No generation engine defined}
