apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-taggroupper
  labels:
    run: news-taggroupper
    {{- include "deep-digest-rss.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.taggroupper.replicas }}
  selector:
    matchLabels:
      run: news-taggroupper
  template:
    metadata:
      labels:
        run: news-taggroupper
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: news-taggroupper
          image: {{ .Values.image.registry }}/{{ .Values.taggroupper.image }}:{{ .Values.taggroupper.tag }}
          {{- with .Values.taggroupper.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.taggroupper.resources | nindent 12 }}
          env:
            - name: NO_ENV_FILE
              valueFrom:
                configMapKeyRef:
                  name: news-config
                  key: NO_ENV_FILE
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: news-config
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: news-secrets
                  key: AUTH_WRITE_PASSWORD
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: news-config
                  key: API_URL
            - name: MODEL
              valueFrom:
                configMapKeyRef:
                  name: news-config
                  key: MODEL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: news-secrets
                  key: API_KEY
            - name: GENERATION_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: news-config
                  key: GENERATION_ENGINE
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
